### PR TITLE
React 16 support

### PR DESCRIPTION
**Pull request by sapegin**
Update peer dependencies to include React 16.

There are no tests so I have no idea if it works ;-)

### CODE REVIEW

**Comment by bebraw** [comment]
At least the function exists... So let's go with this and fix later if needed.

**Comment by bebraw** [comment]
Published as `0.2.0`.

I don't think I'm using the plugin anywhere anymore since my boilerplate moved to something else. Do you want to take over? I can move it below your account and set up rights.

**Comment by sapegin** [comment]
You use it in react-pagify at least ;-)

**Comment by bebraw** [comment]
Ah, yeah... I forgot that. I think it runs on an old version of the boilerplate. I can see why you did this PR now.

**Pull request merged**
